import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, resolve } from "node:path";

import type { ThemeArtifactPaths, ThemeArtifacts, ThemeConfig } from "./types";

function escapeSwift(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function toSnakeCase(input: string): string {
  return input
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[^a-zA-Z0-9_]/g, "_")
    .toLowerCase();
}

function resolveOutputPath(cwd: string, path: string): string {
  return isAbsolute(path) ? path : resolve(cwd, path);
}

function collectTokenEntries(config: ThemeConfig): Array<[string, string]> {
  const { colors, typography, radii, spacing, behavior } = config.tokens;

  const buttonHover = behavior.enableHover ? colors.primaryHover : colors.primary;
  const focusRing = behavior.enableFocusRing ? colors.focusRing : "transparent";

  return [
    ["colorBackgroundPrimary", colors.primary],
    ["colorBackgroundSurface", colors.surface],
    ["colorBackgroundPage", colors.background],
    ["colorTextPrimary", colors.textPrimary],
    ["colorTextInverted", colors.textInverted],
    ["colorTextDanger", colors.danger],
    ["colorBorderMuted", colors.borderMuted],
    ["colorFocusRing", focusRing],
    ["fontFamilySans", typography.fontFamilySans],
    ["fontSizeSm", typography.fontSizeSm],
    ["fontSizeMd", typography.fontSizeMd],
    ["fontSizeLg", typography.fontSizeLg],
    ["fontWeightRegular", typography.fontWeightRegular],
    ["fontWeightMedium", typography.fontWeightMedium],
    ["fontWeightSemibold", typography.fontWeightSemibold],
    ["radiusSm", radii.sm],
    ["radiusMd", radii.md],
    ["radiusLg", radii.lg],
    ["space0", spacing["0"]],
    ["space1", spacing["1"]],
    ["space2", spacing["2"]],
    ["space3", spacing["3"]],
    ["space4", spacing["4"]],
    ["space5", spacing["5"]],
    ["space6", spacing["6"]],
    ["componentButtonBackgroundDefault", colors.primary],
    ["componentButtonBackgroundHover", buttonHover],
    ["componentButtonTextDefault", colors.textInverted],
    ["componentButtonRadiusDefault", radii.md],
    ["componentButtonPaddingX", spacing["4"]],
    ["componentButtonPaddingY", spacing["2"]],
    ["stateHoverEnabled", String(behavior.enableHover)],
    ["stateFocusRingEnabled", String(behavior.enableFocusRing)]
  ];
}

export function generateWebCss(config: ThemeConfig): string {
  const { colors, typography, spacing, radii, behavior } = config.tokens;
  const buttonHover = behavior.enableHover ? colors.primaryHover : colors.primary;
  const focusRing = behavior.enableFocusRing ? colors.focusRing : "transparent";

  return `/**
 * Do not edit directly, this file was auto-generated by jss-theme.
 */

:root {
  --jss-color-background-primary: ${colors.primary};
  --jss-color-background-surface: ${colors.surface};
  --jss-color-background-page: ${colors.background};
  --jss-color-text-primary: ${colors.textPrimary};
  --jss-color-text-inverted: ${colors.textInverted};
  --jss-color-text-danger: ${colors.danger};
  --jss-color-border-muted: ${colors.borderMuted};
  --jss-color-focus-ring: ${focusRing};

  --jss-font-family-sans: ${typography.fontFamilySans};
  --jss-font-size-sm: ${typography.fontSizeSm};
  --jss-font-size-md: ${typography.fontSizeMd};
  --jss-font-size-lg: ${typography.fontSizeLg};
  --jss-font-weight-regular: ${typography.fontWeightRegular};
  --jss-font-weight-medium: ${typography.fontWeightMedium};
  --jss-font-weight-semibold: ${typography.fontWeightSemibold};

  --jss-space-0: ${spacing["0"]};
  --jss-space-1: ${spacing["1"]};
  --jss-space-2: ${spacing["2"]};
  --jss-space-3: ${spacing["3"]};
  --jss-space-4: ${spacing["4"]};
  --jss-space-5: ${spacing["5"]};
  --jss-space-6: ${spacing["6"]};

  --jss-radius-sm: ${radii.sm};
  --jss-radius-md: ${radii.md};
  --jss-radius-lg: ${radii.lg};

  --jss-component-button-background-default: ${colors.primary};
  --jss-component-button-background-hover: ${buttonHover};
  --jss-component-button-text-default: ${colors.textInverted};
  --jss-component-button-radius-default: ${radii.md};
  --jss-component-button-padding-x: ${spacing["4"]};
  --jss-component-button-padding-y: ${spacing["2"]};
}`;
}

export function generateIosSwift(config: ThemeConfig): string {
  const lines = [
    "//",
    "// DesignTokens.swift",
    "//",
    "",
    "// Do not edit directly, this file was auto-generated by jss-theme.",
    "",
    "import Foundation",
    "",
    "public enum DesignTokens {"
  ];

  for (const [key, value] of collectTokenEntries(config)) {
    lines.push(`  public static let ${key} = "${escapeSwift(value)}"`);
  }

  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

export function generateAndroidXml(config: ThemeConfig): string {
  const lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    "",
    "<!--",
    "  Do not edit directly, this file was auto-generated by jss-theme.",
    "-->",
    "<resources>"
  ];

  for (const [key, value] of collectTokenEntries(config)) {
    lines.push(`  <string name="${toSnakeCase(key)}">${escapeXml(value)}</string>`);
  }

  lines.push("</resources>");
  lines.push("");

  return lines.join("\n");
}

export function generateThemeArtifacts(config: ThemeConfig): ThemeArtifacts {
  return {
    webCss: generateWebCss(config),
    iosSwift: generateIosSwift(config),
    androidXml: generateAndroidXml(config)
  };
}

export function writeThemeArtifacts(config: ThemeConfig, cwd = process.cwd()): ThemeArtifactPaths {
  const artifacts = generateThemeArtifacts(config);
  const webCssPath = resolveOutputPath(cwd, config.outputs.web.path);
  const iosSwiftPath = resolveOutputPath(cwd, config.outputs.ios.path);
  const androidXmlPath = resolveOutputPath(cwd, config.outputs.android.path);

  for (const path of [webCssPath, iosSwiftPath, androidXmlPath]) {
    mkdirSync(dirname(path), { recursive: true });
  }

  writeFileSync(webCssPath, artifacts.webCss, "utf8");
  writeFileSync(iosSwiftPath, artifacts.iosSwift, "utf8");
  writeFileSync(androidXmlPath, artifacts.androidXml, "utf8");

  return {
    webCssPath,
    iosSwiftPath,
    androidXmlPath
  };
}
